import Foundation
import SwiftUI

struct SetupContentPreview: Codable, Equatable {
    struct Registration: Codable, Equatable {
        let name: String
        let action: String
        let reason: String
    }
    struct File: Codable, Equatable, Identifiable {
        let id: String
        let path: String
        let kind: String
        let title: String
        let proposedContent: String
        let existingStatus: String
        let conditions: [String]
        let registrations: [Registration]
        let managedBlockAction: String?
        enum CodingKeys: String, CodingKey {
            case id, path, kind, title, conditions, registrations
            case proposedContent = "proposed_content", existingStatus = "existing_status"
            case managedBlockAction = "managed_block_action"
        }
    }
    let schemaVersion: String
    let client: String
    let scope: String
    let cliVersion: String
    let generatedAt: String
    let storeDir: String
    let command: String
    let pythonExecutable: String
    let basis: String
    let limits: [String]
    let files: [File]
    enum CodingKeys: String, CodingKey {
        case client, scope, command, basis, limits, files
        case schemaVersion = "schema_version", cliVersion = "cli_version", generatedAt = "generated_at"
        case storeDir = "store_dir", pythonExecutable = "python_executable"
    }

    func validates(client target: SetupClient, store: URL) -> Bool {
        schemaVersion == "agentacct.setup-preview.v1" && scope == "user" && client == target.rawValue
            && (storeDir as NSString).isAbsolutePath
            && URL(fileURLWithPath: storeDir).standardizedFileURL.resolvingSymlinksInPath() == store
            && !files.isEmpty && files.count <= 12 && Set(files.map(\.id)).count == files.count
            && files.allSatisfy { ($0.path as NSString).isAbsolutePath && !$0.id.isEmpty }
    }
}

enum SetupContentPreviewState: Equatable {
    case idle
    case loading
    case available(SetupContentPreview)
    case unavailable(String)
    case failed(String)
}

@MainActor
struct NativeSetupContentPreviewView: View {
    let state: SetupContentPreviewState
    let onRetry: () -> Void
    @Binding var isExpanded: Bool
    @Environment(\.accessibilityReduceMotion) private var reduceMotion

    var body: some View {
        VStack(alignment: .leading, spacing: Space.m) {
            Text("Proposed managed content").workFont(.titleCard).foregroundStyle(Theme.ink)
            switch state {
            case .idle, .loading:
                HStack(spacing: Space.m) {
                    if !reduceMotion { ProgressView().controlSize(.small) }
                    Text("Reading the packaged recorder's setup preview…")
                        .workFont(.body).foregroundStyle(Theme.muted)
                }
            case .unavailable(let message):
                Label("Content preview unavailable", systemImage: "doc.questionmark")
                    .workFont(.rowLabel).foregroundStyle(Theme.amber)
                Text(message).workFont(.body).foregroundStyle(Theme.muted)
            case .failed(let message):
                Label("Content preview could not be read", systemImage: "exclamationmark.triangle")
                    .workFont(.rowLabel).foregroundStyle(Theme.coral)
                Text(message).workFont(.body).foregroundStyle(Theme.muted)
                Button("Retry preview", action: onRetry).buttonStyle(QuietButtonStyle(tint: Theme.accent))
            case .available(let preview):
                Text("Generated by recorder \(preview.cliVersion). \(preview.basis)")
                    .workFont(.body).foregroundStyle(Theme.muted)
                    .fixedSize(horizontal: false, vertical: true)
                DisclosureGroup("Inspect instructions, commands, and registration changes", isExpanded: $isExpanded) {
                    VStack(alignment: .leading, spacing: Space.l) {
                        Text("Preview generated: \(preview.generatedAt)")
                            .workFont(.dataSmall).foregroundStyle(Theme.muted).textSelection(.enabled)
                        ForEach(preview.limits, id: \.self) { limit in
                            Text(limit).workFont(.caption).foregroundStyle(Theme.muted)
                                .fixedSize(horizontal: false, vertical: true)
                        }
                        ForEach(preview.files) { file in fileContent(file) }
                    }
                    .padding(.top, Space.m)
                }
                .workFont(.rowLabel).foregroundStyle(Theme.ink)
                Button("Refresh preview", action: onRetry)
                    .buttonStyle(QuietButtonStyle(tint: Theme.accent))
            }
        }
        .workFont(.body)
        .padding(Space.cardPad)
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(Theme.card, in: RoundedRectangle(cornerRadius: Metrics.radius))
        .overlay(RoundedRectangle(cornerRadius: Metrics.radius).strokeBorder(Theme.cardLine))
        .accessibilityElement(children: .contain)
        .accessibilityIdentifier("setup-content-preview")
    }

    private func fileContent(_ file: SetupContentPreview.File) -> some View {
        VStack(alignment: .leading, spacing: Space.m) {
            VStack(alignment: .leading, spacing: Space.s) {
                Text(file.title).workFont(.rowLabel).foregroundStyle(Theme.ink)
                Text(file.path).workFont(.dataSmall).foregroundStyle(Theme.muted).textSelection(.enabled)
                    .fixedSize(horizontal: false, vertical: true)
                Text("Existing file: \(file.existingStatus.replacingOccurrences(of: "_", with: " "))")
                    .workFont(.captionSemibold)
                    .foregroundStyle(["absent", "inspected"].contains(file.existingStatus) ? Theme.muted : Theme.amber)
            }
            if let action = file.managedBlockAction {
                Text("Managed instruction block: \(action)").workFont(.caption).foregroundStyle(Theme.ink)
            }
            ForEach(file.registrations, id: \.name) { registration in
                VStack(alignment: .leading, spacing: Space.xs) {
                    Text("\(registration.name) · \(registration.action)")
                        .workFont(.dataSmallSemibold).foregroundStyle(Theme.ink)
                    Text(registration.reason).workFont(.caption).foregroundStyle(Theme.muted)
                        .fixedSize(horizontal: false, vertical: true)
                }
            }
            ForEach(file.conditions, id: \.self) { condition in
                Text(condition).workFont(.caption).foregroundStyle(Theme.muted)
                    .fixedSize(horizontal: false, vertical: true)
            }
            NativeSetupGeneratedContentView(content: file.proposedContent, fileID: file.id)
            Divider().overlay(Theme.cardLine)
        }
    }
}

@MainActor
private struct NativeSetupGeneratedContentView: View {
    let content: String
    let fileID: String
    @State private var isExpanded = SnapshotMode.enabled && SnapshotMode.reviewExpandSetupDetails
    private var layout = NativeSetupLayout()

    init(content: String, fileID: String) {
        self.content = content
        self.fileID = fileID
    }

    var body: some View {
        DisclosureGroup("Read generated content", isExpanded: $isExpanded) {
            ScrollView([.horizontal, .vertical]) {
                Text(content).workFont(.dataSmall).foregroundStyle(Theme.ink)
                    .textSelection(.enabled).padding(Space.m)
                    .frame(maxWidth: .infinity, alignment: .leading)
            }
            .frame(height: layout.generatedContentHeight)
            .background(Theme.chrome, in: RoundedRectangle(cornerRadius: Metrics.radius))
            .accessibilityIdentifier("setup-generated-content-\(fileID)")
        }
        .workFont(.captionSemibold)
    }
}
